language: node_js
sudo: required
node_js:
  - lts/*
cache: npm
install:
  - npm ci
  - npm i react-scripts
before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
script:
  - npm test
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
branches:
  only:
  - main
  - develop
  - B#10
